<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$_product = $block->getProduct();
$helper = $this->helper('Magedelight\Orderbysku\Helper\Productdetail');
?>
<?php /* @var $block \Magento\GiftCard\Block\Catalog\Product\View\Type\Giftcard */?>

<div class="giftcard form" data-container-for="giftcard_info">
  <fieldset class="fieldset giftcard-amount">
  <div id="giftcard-amount-box" class="field required open-amount">
    <label for="giftcard-amount-input" id="amount-label-input" class="label">
        <span><?= /* @escapeNotVerified */ __('Amount in %1', $block->getCurrentCurrency()) ?></span>
    </label>
    <div class="control">
        <input type="text" id="giftcard-amount-input" name="custom_giftcard_amount" class="input-text"
               data-validate="{number: true, required: true
                                <?php if ($helper->getOpenAmountMin($_product)) {
                   echo ',min: ';
                   /* @escapeNotVerified */ echo $helper->convertCurrency($helper->getOpenAmountMin($_product));
               }
               if ($helper->getOpenAmountMax($_product)) {
                   echo ',max: ';
                   /* @escapeNotVerified */ echo $helper->convertCurrency($helper->getOpenAmountMax($_product));
               }
               ?>
               }" value="<?= $block->escapeHtml($helper->getOpenAmountMin($_product)) ?>" />

        <?php if ($helper->getOpenAmountMin($_product) || $helper->getOpenAmountMax($_product)): ?>
            <?php $min = $helper->convertAndFormatCurrency($helper->getOpenAmountMin($_product), false); ?>
            <?php $max = $helper->convertAndFormatCurrency($helper->getOpenAmountMax($_product), false); ?>
            <p class="note">
                <?php if ($helper->getOpenAmountMax($_product) && $helper->getOpenAmountMin($_product)): ?>
                    <span><?= /* @escapeNotVerified */ __('Minimum: %1', $min) ?></span>
                    <span><?= /* @escapeNotVerified */ __('Maximum: %1', $max) ?></span>
                <?php elseif ($helper->getOpenAmountMin($_product)): ?>
                    <span><?= /* @escapeNotVerified */ __('Minimum: %1', $min) ?></span>
                <?php elseif ($helper->getOpenAmountMax($_product)): ?>
                    <span><?= /* @escapeNotVerified */ __('Maximum: %1', $max) ?></span>
                <?php endif; ?>
            </p>
        <?php endif; ?>
    </div>
  </div>
  </fieldset>

<?php $_id = $_product->getId(); ?>
    <?= $block->getChildHtml('product_type_data_extra') ?>

    <?php if ($_product->isSaleable() && $block->isConfigured($_product)): ?>
        <fieldset class="fieldset giftcard send">
            <div class="field sender required">
                <label for="giftcard_sender_name" class="label"><span><?= /* @escapeNotVerified */ __('Sender Name') ?></span></label>
                <div class="control">
                    <input type="text"
                           id="giftcard_sender_name"
                           name="giftcard_sender_name"
                           class="required-entry input-text"
                           value="<?= $block->escapeHtml($block->getDefaultSenderName()) ?>" />
                </div>
            </div>
            <?php if ($block->isEmailAvailable($_product)): ?>
                <div class="field sender email required">
                    <label for="giftcard_sender_email" class="label"><span><?= /* @escapeNotVerified */ __('Sender Email') ?></span></label>
                    <div class="control">
                        <input type="email"
                               id="giftcard_sender_email"
                               name="giftcard_sender_email"
                               class="validate-email required-entry input-text"
                               value="<?= $block->escapeHtml($block->getDefaultSenderEmail()) ?>"/>
                    </div>
                </div>
            <?php endif; ?>

            <div class="field recipient required">
                <label for="giftcard_recipient_name" class="label"><span><?= /* @escapeNotVerified */ __('Recipient Name') ?></span></label>
                <div class="control">
                    <input type="text"
                           id="giftcard_recipient_name"
                           name="giftcard_recipient_name"
                           class="required-entry input-text"
                           value="<?= $block->escapeHtml($block->getDefaultValue('giftcard_recipient_name')) ?>" />
                </div>
            </div>
            <?php if ($block->isEmailAvailable($_product)): ?>
                <div class="field recipient email required">
                    <label for="giftcard_recipient_email" class="label"><span><?= /* @escapeNotVerified */ __('Recipient Email') ?></span></label>
                    <div class="control">
                        <input type="email"
                               id="giftcard_recipient_email"
                               name="giftcard_recipient_email"
                               class="validate-email required-entry input-text"
                               value="<?= $block->escapeHtml($block->getDefaultValue('giftcard_recipient_email')) ?>" />
                    </div>
                </div>
            <?php endif; ?>

            <?php if ($block->isMessageAvailable($_product)): ?>
                <div class="field text">
                    <label for="giftcard-message" class="label"><span><?= /* @escapeNotVerified */ __('Message') ?></span></label>
                    <div class="control">
                        <textarea name="giftcard_message" id="giftcard-message" class="input-text giftcard-message-max-length"
                            <?php if ($block->getMessageMaxLength()) {
    $errorMessage = "'" . __('Maximum length of the message is %1 characters.', $block->getMessageMaxLength()) . "'";
                                /* @escapeNotVerified */ echo 'data-validate="{maxlength:' . $block->getMessageMaxLength() . ',messages:{maxlength:' . $errorMessage . '}}"';
} ?>
                            cols="5" rows="3"><?= $block->escapeHtml($block->getDefaultValue('giftcard_message')) ?></textarea>
                    </div>
                </div>
            <?php endif; ?>
        </fieldset>
    <?php elseif ($_product->isAvailable() && $block->isConfigured($_product)): ?>
        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
    <?php endif; ?>
</div>
