<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<span data-action="toggle-nav" class="action nav-toggle"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span>

<?php  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface'); $storeID = $storeManager->getStore()->getStoreId(); $storeName = $storeManager->getStore()->getCode();?>
<a
        class="logo"
        href="<?= $block->getUrl('') ?>"
        title="<?= /* @escapeNotVerified */ $storeName ?>"
        aria-label="store logo">
    <?php if($storeName == "en"){ ?>
        <img class="test" src="<?php echo $this->getViewFileUrl('images/logo.svg'); ?>"
             title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
             alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
            <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
            <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />
    <?php  } else { ?>
        <img class="test" src="<?php echo $this->getViewFileUrl('images/logo-fr.svg'); ?>"
             title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
             alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
            <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
            <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />
    <?php } ?>
</a>
