<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
//$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$productId = $block->getSaleableItem()->getId();
$product = $objectManager->get('\Magento\Catalog\Model\Product')->load($productId);

$productModel = $this->helper('LeanSwift\Turfcare\Helper\Productdetail')->getLoadedProduct($product);
$customerSession = $objectManager->get('Magento\Customer\Model\SessionFactory')->create();
$customerData = $customerSession->getCustomer();	$listPrice = $priceModel->getAmount();
$erpCustomerCodes = explode(",", $customerData->getErpCustomerCode());
$erpProductCategoryCode=explode(",", $productModel->getErpProductCategoryCode());
$listPrice = $priceModel->getAmount();
$finalPrice = $finalPriceModel->getAmount();
$flag=false;
if(count($erpProductCategoryCode) > 0) {
    foreach($erpProductCategoryCode as $ProductCategoryCode) {
        if(in_array($ProductCategoryCode,$erpCustomerCodes)) {
            $flag=true;
            break;
        }
    }
}
if($schema) {
    $condition = $customerSession->isLoggedIn() && ($flag==1) && !empty($productModel->getErpProductCategoryCode());
}else{
    $condition = $customerSession->isLoggedIn();
}
if($condition):?>
    <?php if ($block->hasSpecialPrice()): ?>
        <span class="special-price">

        <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Your Cost'),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
        <span class="your-cost"><?php echo __("Your Cost");?></span>

    </span>

        <br />
        <span class="old-price">

        <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('List Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
        <span class="your-cost"><?php echo __("List Price");?></span>
    </span>
    <?php elseif($finalPrice > $listPrice): ?>
        <span class="special-price">
	    <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
        <span class="your-cost"><?php echo __("Your Cost");?></span>
	</span>

    <?php else: ?>
        <span class="old-price-new">
	    <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
        <span class="your-cost"><?php echo __("List Price");?></span>
	</span>
    <?php endif; ?>

    <?php if ($block->showMinimalPrice()): ?>
        <?php if ($block->getUseLinkForAsLowAs()):?>
            <a href="<?= /* @escapeNotVerified */ $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
                <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
            </a>
        <?php else:?>
            <span class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </span>
        <?php endif?>
    <?php endif; ?>
<?php endif; ?>