<?php
    $_helper = $this->helper('WeltPixel\ThankYouPage\Helper\Data');
    $_order = $block->getLastOrder();
    $items = $_order->getAllVisibleItems();

?>
<div class="order-info" >
    <?php if ($_helper->showCustomerInfo()): ?>
        <div class="customer-info">
            <h4><?= /* @escapeNotVerified */ __('Customer Information') ?></h4>
            <div class="address-wrapper">
                <div class="shipping-address col-lg-3 col-md-3 col-xs-3">
                    <h4><?= /* @escapeNotVerified */ __('Shipping Address') ?></h4>
                    <p>
                        <?php if ($_order->getShippingAddress()): ?>
                            <?= /* @escapeNotVerified */ $block->getFormattedAddress($_order->getShippingAddress()) ?>
                        <?php else: ?><?= __('No shipping address') ?>
                        <?php endif; ?>
                    </p>
                </div>
                <div class="shipping-method col-lg-3 col-md-3 col-xs-3">
                    <h4><?= /* @escapeNotVerified */ __('Shipping Method') ?></h4>
                    <p>
                        <?php if ($block->getShippingMethodTitle($_order)): ?>
                            <?= /* @escapeNotVerified */ $block->getShippingMethodTitle($_order) ?>
                        <?php else: ?>
                            <?= __('No shipping method') ?>
                        <?php endif; ?>
                    </p>
                </div>
                <div class="billing-address col-lg-3 col-md-3 col-xs-3">
                    <h4><?= /* @escapeNotVerified */ __('Billing Address') ?></h4>
                    <p><?= /* @escapeNotVerified */ $block->getFormattedAddress($_order->getBillingAddress()) ?></p>
                </div>
                <div class="payment-method col-lg-3 col-md-3 col-xs-3">
                    <h4><?= /* @escapeNotVerified */ __('Payment Method') ?></h4>
                    <p><?= /* @escapeNotVerified */ $block->getPaymentMethodTitle($_order) ?></p>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <?php if ($_helper->showProductInfo()): ?>

        <div class="product-grid">
            <ul class="items order-links">
                <li class="nav item current">
                    <strong>Items Ordered</strong>
                </li>
            </ul>
            <div class="table-wrapper order-items">
                <table class="data table table-order-items" id="table-order-items">
                    <thead>
                        <tr>
                            <th class="col image textalign-left"><?= /* @escapeNotVerified */ __('Image') ?></th>
                            <th class="col name textalign-left"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
                            <th class="col sku textalign-left"><?= /* @escapeNotVerified */ __('SKU') ?></th>
                            <th class="col price textalign-right"><?= /* @escapeNotVerified */ __('Price') ?></th>
                            <th class="col qty textalign-center"><?= /* @escapeNotVerified */ __('Qty') ?></th>
                            <th class="col subtotal textalign-right"><?= /* @escapeNotVerified */ __('Subtotal') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?= $this->getChildHtml('order.items'); ?>
                    </tbody>
                    <tfoot>
                        <?= $this->getChildHtml('order.totals'); ?>
                    </tfoot>
                </table>
                <span class="total-notification"><?= /* @escapeNotVerified */ __('Please note order total does not include freight.  Regular shipping charges will be applied at the time of shipping and be reflected on the invoice.') ?></span>
            </div>
        </div>
    <?php endif; ?>
</div>