<?php
// @codingStandardsIgnoreFile
?>
<?php $_helper = $this->helper('WeltPixel\Multistore\Helper\Data'); ?>
<?php $_utilityHelper = $this->helper('WeltPixel\Backend\Helper\Utility'); ?>
<?php if (count($block->getStores())>1): ?>
    <?php $bgColorStyle = $_helper->getBarBgColor() ? "style='background-color: ".$_helper->getBarBgColor() ."'" : ''?>
<div id="multistore-mobile-switcher-language"
    <?php if ($_helper->displayInOneRow()) : ?>
        class="multistore-desktop"
        <?php endif; ?>
    <?=$bgColorStyle?>
    style="display:none;">
    <div class="store-options">
        <ul class="weltpixel_multistore">
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php if (!$_helper->canStoreBeDisplayed($_lang->getId(), $_lang->getCode())) continue; ?>
                <?php $image = $_helper->getImageUrl($_lang->getId());  ?>
                <?php $inactiveImage = $_helper->getInactiveImageUrl($_lang->getId()); ?>
                <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> <?php if ($_lang->getId() == $block->getCurrentStoreId()): echo 'active'; endif; ?>  switcher-option">
                    <?php if ($_lang->getId() == $block->getCurrentStoreId()): ?>
                        <img src="<?php echo $image ?>" alt="<?php echo $block->escapeHtml($_lang->getName()) ?>" />
                    <?php else: ?>
                        <!--<a href="#" data-post='<?php /*/* @escapeNotVerified */ //echo $block->getTargetStorePostData($_lang); */?>'>
                            <img src="<?php /*echo $inactiveImage */?>" alt="<?php /*echo $block->escapeHtml($_lang->getName()) */?>" />
                        </a>-->
                    <!-- TC-221: Alternative fix for redirect the store view url in mobile devices -->
                    <a href="<?php echo substr($block->getBaseUrl(),0, -3).$_lang->getCode(); ?>">
                        <img src="<?php echo $inactiveImage ?>" alt="<?php echo $block->escapeHtml($_lang->getName()) ?>" />
                    </a>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<style>
    <?php
    $imgHeight = $_helper->getImageHeight();
    $imgWidth = $_helper->getImageWidth();
    $barWidth = $_helper->getBarWidth();
    ?>
    ul.weltpixel_multistore li img {
        height: <?php echo $imgHeight; ?>;
        <?php if ($imgWidth) : ?>
        width: <?php echo $imgWidth; ?>;
        <?php endif; ?>
    }
    <?php if(!$_utilityHelper->isPearlThemeUsed() && $barWidth):?>
    @media screen and (min-width: 768px) {
        .weltpixel_multistore {
            max-width: <?php echo $barWidth;?>
        }
    }
    <?php endif;?>
</style>
<?php endif; ?>

<script>
    require([
        'jquery'
    ], function ($) {

        $( document ).ready(function() {
            if ($(window).width() < '767') {
                $('.header-multistore').appendTo('.nav-sections-items');
                $('.header-multistore').css({"padding-top": "20px"});
                $('.nav-sections-items #multistore-mobile-switcher-language').css({"display": "block"});
                $('.custom-top-links').appendTo('.navigation');
            }
        });
    });
</script>
