<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_turfcareHelper = $this->helper('LeanSwift\Turfcare\Helper\Data'); ?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php $buttonTitleLogin = __('Log In to See Pricing'); ?>
<?php $addToCartClass = !$block->shouldRenderQuantity() ? 'full-width-btn' : ''; ?>
<?php
$allowCart = true;
?>
<?php
$om = \Magento\Framework\App\ObjectManager::getInstance();
$request = $om->get('Magento\Framework\App\Request\Http');
$previousURL = $request->getServer('HTTP_REFERER');
$customerSession = $om->get('Magento\Customer\Model\SessionFactory')->create();
$customerData = $customerSession->getCustomer();
$erpCustomerCodes = explode(",", $customerData->getErpCustomerCode());
$erpProductCategoryCode=explode(",", $_product->getErpProductCategoryCode());
$flag=false;
if(count($erpProductCategoryCode) > 0) {
    foreach($erpProductCategoryCode as $ProductCategoryCode) {
        if(in_array($ProductCategoryCode,$erpCustomerCodes)) {
            $flag=true;
            break;
        }
    }
}

if($customerSession->isLoggedIn()){
    if(!empty($_product->getErpProductCategoryCode()) && ($flag==1)){
        $hideproductInfo = 0;
    }else{
        $hideproductInfo = 1;
    }
}else{
    $hideproductInfo = 0;
}
?>
<?php
if ($customerSession->isLoggedIn() && ($flag==1) && !empty($_product->getErpProductCategoryCode())):
    ?>
    <?php if ($_product->isSaleable() && $allowCart): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= /* @escapeNotVerified */
                            __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               min="0"
                               value="<?= /* @escapeNotVerified */
                               $block->getProductDefaultQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */
                               __('Qty') ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= /* @escapeNotVerified */
                        $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= /* @escapeNotVerified */
                        $buttonTitle ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php else: ?>
    <div class="box-tocart">
        <?php
        if($customerSession->isLoggedIn()) :?>
            Please contact our Customer Service department for further details<br><br>

            1-800-561-8873 EN<br><br>

            1-800-363-9914 FR
        <?php else: ?>
        <div class="fieldset">
            <div class="actions">
                <?php
                $url  = $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
                $login_url = $block->getUrl('customer/account/login', array('referer' => base64_encode($url)));
                ?>
                <button type="button" style="width:100%;" style="width:100%;" onclick="window.location.href='<?php echo $login_url; ?>'"
                        title="<?php /* @escapeNotVerified */
                        echo $buttonTitleLogin ?>"
                        class="primary">
                    <span><?php /* @escapeNotVerified */
                        echo $buttonTitleLogin ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
<script>
    require([
        'jquery'
    ], function($){
        $(document).ready( function() {
            var hideinfo = "<?php echo $hideproductInfo;?>";
            if(hideinfo > 0){
                $('.product-info-stock-sku').hide();
            }
            $(".bg-accordion").click(function(){
                $(this).next('.cnt-acc').toggle();
            });
            $(".no-border-accordion").click(function(){
                $(this).next('.content.no-border-accordion').toggle();
            });
        });
    });
</script>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }

</script>
