<?php
/**
* Setubridge Technolabs
* http://www.setubridge.com/
* @author SetuBridge
* @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
**/

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$itemInfo = [];
$_item = $block->getItem();
$product = $_item->getProduct();
$turfcareHelper = $this->helper('LeanSwift\Turfcare\Helper\Data');
if($product->getId()){
    $itemInfo = $turfcareHelper->getCartItemData($product);
}
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);

$helperCartProduct = $this->helper('SetuBridge\CartProductComment\Helper\Data');
$cartCommentStatus = $helperCartProduct->getStatus();
$placeholderText = $helperCartProduct->getPlaceholderText();
?>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
            <?php if ($block->hasProductUrl()):?>
                <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"
                    title="<?= $block->escapeHtml($block->getProductName()) ?>"
                    tabindex="-1"
                    class="product-item-photo">
                    <?php else:?>
                    <span class="product-item-photo">
                    <?php endif;?>
                <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
                <?php if ($block->hasProductUrl()):?>
                </a>
                <?php else: ?>
                </span>
                <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()):?>
                        <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                        <?php else: ?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                        <?php endif; ?>
                </strong>
                <div class="item-info-container">
                    <div class="product-item-number"><span class="item-number-label"><?= $block->escapeHtml(__('Item# :')) ?></span><?= $block->escapeHtml($itemInfo['sxe_product_number']) ?> </div>
                    <div class="product-item-avaiableqty"><span class="item-qty-label"><?= $block->escapeHtml(__('Stock :')) ?></span><?= $block->escapeHtml($itemInfo['qty']) ?> </div>
                </div>
                <?php if ($_options = $block->getOptionList()):?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <?= /* @escapeNotVerified */ $_formatedOptionValue['full_view'] ?>
                                    <?php else: ?>
                                    <?= /* @escapeNotVerified */ $_formatedOptionValue['value'] ?>
                                    <?php endif; ?>
                            </dd>
                            <?php endforeach; ?>
                    </dl>
                    <?php endif;?>
                <?php if ($messages = $block->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class="cart item message <?= /* @escapeNotVerified */ $message['type'] ?>"><div><?= $block->escapeHtml($message['text']) ?></div></div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                    <?php endif;?>
            </div>
        </td>

        <?php if ($canApplyMsrp): ?>
            <td class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= /* @escapeNotVerified */ __('See price before order confirmation.') ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?= /* @escapeNotVerified */ ($helpLinkId) ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?= /* @escapeNotVerified */ $helpLinkId ?>","productName": "<?= /* @escapeNotVerified */ $product->getName() ?>","showAddToCart": false}}'>
                        <span><?= /* @escapeNotVerified */ __("What's this?") ?></span>
                    </a>
                </span>
            </td>
            <?php else: ?>
            <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <?= $block->getUnitPriceHtml($_item) ?>
            </td>
            <?php endif; ?>
        <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
            <div class="field qty">
                <label class="label" for="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty">
                    <span><?= /* @escapeNotVerified */ __('Qty') ?></span>
                </label>
                <div class="control qty">
                    <input id="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty"
                        name="cart[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]"
                        data-cart-item-id="<?= $block->escapeHtml($_item->getSku()) ?>"
                        value="<?= /* @escapeNotVerified */ $block->getQty() ?>"
                        type="number"
                        size="4"
                        title="<?= $block->escapeHtml(__('Qty')) ?>"
                        class="input-text qty"
                        data-validate="{required:true,'validate-greater-than-zero':true}"
                        data-role="cart-item-qty"/>
                </div>
            </div>
        </td>

        <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
            <?php if ($canApplyMsrp): ?>
                <span class="cart msrp subtotal">--</span>
                <?php else: ?>
                <?= $block->getRowTotalHtml($_item) ?>
                <?php endif; ?>
        </td>

        <?php if($cartCommentStatus){ ?>
            <td class="col">
                <textarea rows="4" placeholder="<?php if($placeholderText){echo $placeholderText;} else{echo __('Comment');} ?>" data-item_id="<?= $block->escapeHtml($_item->getItemId()) ?>" class="comment product-comment-input" name="cart[<?= $block->escapeHtml($_item->getItemId()) ?>][product_comment]"><?= $block->escapeHtml($_item->getProductComment()) ?></textarea>
            </td>
            <?php } ?>
    </tr>
    <tr class="item-actions">
        <td colspan="100">
            <div class="actions-toolbar">
                <?= /* @escapeNotVerified */ $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
</tbody>
<script type="text/javascript">
    require(['jquery','jquery/ui'], function ($) {
        $(document).ready(function(){
            var url = '<?php echo $block->getBaseUrl() ?>cartproductcomment/cart/addcomment';
            jQuery('.comment.product-comment-input').off("change").on('change',function(){
                var comment = $(this).val();
                var item_id = $(this).data("item_id");
                $.ajax({
                    url: url,
                    data: {'item_id': item_id,'product_comment':comment},
                    type: 'post',
                    dataType: 'json',
                    showLoader: true,
                    success: function (response) {
                        if (response.error) {

                            var html_message = '<div class="messages"><div class="message message-error error">'+response.message+'</div></div>';

                            if($('#maincontent .page.messages .message').length){
                                $('#maincontent .page.messages .message').remove();
                                $('#maincontent .page.messages').html(html_message);
                            }
                            else{
                                $('#maincontent .page.messages').html(html_message);
                            }
                            setTimeout(function(){
                                if($('#maincontent .page.messages .message').length){
                                    $('#maincontent .page.messages .message').remove();
                                }
                                },6000);

                        } else {
                            var html_message = '<div class="messages"><div class="message message-success success">'+response.message+'</div></div>';
                            if($('#maincontent .page.messages .message').length){
                                $('#maincontent .page.messages .message').remove();
                                $('#maincontent .page.messages').html(html_message);
                            }
                            else{
                                $('#maincontent .page.messages').html(html_message);
                            }
                            setTimeout(function(){
                                if($('#maincontent .page.messages .message').length){
                                    $('#maincontent .page.messages .message').remove();
                                }
                                },6000);
                        }

                    },
                    error:function(){
                        var html_message = '<div class="messages"><div class="message message-error error">Sometime error.please try again!</div></div>';

                        if($('#maincontent .page.messages .message').length){
                            $('#maincontent .page.messages .message').remove();
                            $('#maincontent .page.messages').html(html_message);
                        }
                        else{
                            $('#maincontent .page.messages').html(html_message);
                        }
                        setTimeout(function(){
                            if($('#maincontent .page.messages .message').length){
                                $('#maincontent .page.messages .message').remove();
                            }
                            },6000);
                    }
                });
            });
        });
    });

</script>