<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_ctosHelper = $this->helper('LeanSwift\Turfcare\Helper\Data'); ?>
<?php $_product = $block->getProduct(); ?>
<?php $previousURL = $_product->getProductUrl();?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php $buttonTitleLogin = __('Log In to See Pricing'); ?>
<?php $addToCartClass = !$block->shouldRenderQuantity() ? 'full-width-btn' : ''; ?>
<?php $supersededSku = $_product->getSupersedes();
$_ctosHelper->isSupersededItemExist($supersededSku);
$validationResult = $_ctosHelper->isSupersededItemExist($supersededSku);
$allowCart = true;
if($supersededSku && $_ctosHelper->isSupersededItemExist($supersededSku)){
    $allowCart = false;
}?>

<?php
$om = \Magento\Framework\App\ObjectManager::getInstance();
$request = $om->get('Magento\Framework\App\Request\Http');
$customerSession = $om->get('Magento\Customer\Model\SessionFactory')->create();
$customerData = $customerSession->getCustomer();
$erpCustomerCodes = explode(",", $customerData->getErpCustomerCode());
$erpProductCategoryCode=explode(",", $_product->getErpProductCategoryCode());
$flag=false;
if(count($erpProductCategoryCode) > 0) {
    foreach($erpProductCategoryCode as $ProductCategoryCode) {
        if(in_array($ProductCategoryCode,$erpCustomerCodes)) {
            $flag=true;
            break;
        }
    }
}

if($customerSession->isLoggedIn()){
    if(!empty($_product->getErpProductCategoryCode()) && ($flag==1)){
        $hideproductInfo = 0;
    }else{
        $hideproductInfo = 1;
    }
}else{
    $hideproductInfo = 0;
}
?>
<?php
if ($customerSession->isLoggedIn() && ($flag==1) && !empty($_product->getErpProductCategoryCode())):
    ?>
    <?php if ($_product->isSaleable() && $allowCart): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */
                            echo __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               maxlength="12"
                               value="<?php /* @escapeNotVerified */
                               echo $block->getProductDefaultQty() * 1 ?>"
                               title="<?php /* @escapeNotVerified */
                               echo __('Qty') ?>" class="input-text qty"
                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */
                        echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?php /* @escapeNotVerified */
                        echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php else: ?>
    <div class="box-tocart">
        <?php
        if ($customerSession->isLoggedIn()) : ?>
            Please contact our Customer Service department for further details<br><br>

            1-800-561-8873 EN<br><br>

            1-800-363-9914 FR<br><br>
        <?php else: ?>
            <div class="fieldset">
                <div class="actions">

                    <?php
                    $url  = $this->getUrl('*/*/*', ['_current' => false, '_use_rewrite' => true]);
                    $login_url = $block->getUrl('customer/account/login', array('referer' => base64_encode($previousURL)));
                    ?>
                    <a target="_parent" href="<?php echo $login_url; ?>" title="Login to see pricing" class="action primary" id="login-button">
                        <span>Login to see pricing</span>
                    </a>
                    <?php echo $block->getChildHtml('', true) ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }

    </script>
<?php else : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';

            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).catalogAddToCart({
                        bindSubmit: false
                    });

                    widget.catalogAddToCart('submitForm', $(form));

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>
<script>
    require([
        'jquery'
    ], function($){
        $(document).ready( function() {
            var hideinfo = "<?php echo $hideproductInfo;?>";
            if(hideinfo > 0){
                $('.product-info-stock-sku').hide();
            }
        });
    });
</script>
